const actionType = {
   //Aside
   OPEN_ASIDE : "OPEN_ASIDE",
   CLOSE_ASIDE : "CLOSE_ASIDE",
   //Product
   SET_PRODUCTS_DATA : "SET_PRODUCTS_DATA",
   SET_PRODUCT_DATA : "SET_PRODUCT_DATA",
   //Cart
   CART_ADD_ITEM : "CART_ADD_ITEM",
   CART_REMOVE_ITEM : "CART_REMOVE_ITEM",
   USER_SIGNIN_REQUEST : 'USER_SIGNIN_REQUEST',
   USER_SIGNIN_SUCCESS : 'USER_SIGNIN_SUCCESS',
   USER_SIGNIN_FAIL : 'USER_SIGNIN_FAIL',
   //User
   USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
   USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
   USER_REGISTER_FAIL : 'USER_REGISTER_FAIL',
};
export default actionType;

